"""empty message

Revision ID: c22ea2479b90
Revises: 
Create Date: 2022-03-26 15:45:30.532345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22ea2479b90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_purchase_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('discount_purchase_info_indices', 'discount_purchase_info', ['store_id', 'brand_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_discount_purchase_info_brand_id'), 'discount_purchase_info', ['brand_id'], unique=False)
    op.create_index(op.f('ix_discount_purchase_info_product_id'), 'discount_purchase_info', ['product_id'], unique=False)
    op.create_index(op.f('ix_discount_purchase_info_store_id'), 'discount_purchase_info', ['store_id'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('percentage', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('purchase_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_info_id'], ['discount_purchase_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_code'), 'discount', ['code'], unique=True)
    op.create_index(op.f('ix_discount_created_at'), 'discount', ['created_at'], unique=False)
    op.create_index(op.f('ix_discount_user_id'), 'discount', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discount_user_id'), table_name='discount')
    op.drop_index(op.f('ix_discount_created_at'), table_name='discount')
    op.drop_index(op.f('ix_discount_code'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_discount_purchase_info_store_id'), table_name='discount_purchase_info')
    op.drop_index(op.f('ix_discount_purchase_info_product_id'), table_name='discount_purchase_info')
    op.drop_index(op.f('ix_discount_purchase_info_brand_id'), table_name='discount_purchase_info')
    op.drop_index('discount_purchase_info_indices', table_name='discount_purchase_info')
    op.drop_table('discount_purchase_info')
    # ### end Alembic commands ###
